### ISSUE TITLE
Chain ID for Mara testnet is identical to the chain ID for ADIL Devnet

### ISSUE THREAD

**Issue by timothyAgevi** [mara-labs/mara-chain#176]
System info:[Include Mara-chain commit, Linux Operating System .

 I expect Mara to have unique chain ID .

Chain ID for Mara testnet is identical to the chain ID for ADIL Testnet.

Below are attached screenshots showing mara 's chain ID on the exporer i.e https://testnet.mara.xyz/ and one for Metamask once connected to ADIL network.
 
![Mara ChainID](https://github.com/mara-labs/mara-chain/assets/47734891/f1374a36-3727-4d1a-aa9d-c9636dda6155)
![ADIL Devnet ChainID](https://github.com/mara-labs/mara-chain/assets/47734891/bfd69f5d-8546-4838-9c39-fc24338ff619)

This is hindering integration of frony=tend and smart contrax-ct.

Best Regards.

**Comment by blewater** [comment]
This is the wrong chain repo, @timothyAgevi, I'll respond to your email message with the new ID.
